authors:
  Lenny:
    name: Lenny Chen    # Author name
    description: How do you define it? # Author description
    avatar: https://s2.loli.net/2024/03/31/Ht3QBqhgLYNAuwj.png
    # avatar: https://s1.imagehub.cc/images/2024/02/02/91a767e93d1a344e44c69936464c583e.png         # Author avatar
